MooMa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('showform/', include('contactus.urls')),
    path('aboutus/', include('aboutus.urls')),
    path('technology/', include('technology.urls')),
    path('farmerlogin/', include('farmerlogin.urls')),
    path('visual/', include('visual.urls')),
    path('financierlogin/', include('financierlogin.urls')),
    path('visualfinancier/', include('visualfinancier.urls')),
]

aboutus/urls.py
from django.urls import re_path, include, path
from . import views

app_name = 'aboutus'

urlpatterns = [

    path('', views.aboutus, name='aboutus'),
]

contactus/urls.py
from django.urls import re_path, include, path
from . import views

app_name = 'contactus'


urlpatterns = [

    path('', views.showform, name='showform'),

]

farmerlogin/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views


app_name = 'farmerlogin'

urlpatterns = [
    path('',views.userlogin,name='userlogin'),
    path('logout/',views.userlogout,name='userlogout'),
    #path('',auth_views.login,{'template_name': 'farmerlogin/login.html'},name='login'),
    path('signup/', views.signup, name='signup'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    path('ajax/load_districts/', views.load_districts, name='load_districts'),
    path('ajax/load_subdistricts/', views.load_subdistricts, name='load_subdistricts'),
    path('ajax/load_pincode/', views.load_pincode, name='load_pincode'),
]

home/urls.py
from django.urls import re_path, include, path
from . import views

app_name = 'home'

urlpatterns = [
    #path('load/',views.load,name='load'),
    path('', views.home, name='home'),
]

technology/urls.py
from django.urls import re_path, include, path
from . import views

app_name = 'technology'

urlpatterns = [

    path('', views.technology, name='technology'),
]

visual/urls.py
from django.urls import path
from . import views

app_name = 'visual'

urlpatterns = [
    path('',views.visual,name='visual'),
    path('quantity/',views.quantity,name='quantity'),
    path('quality/',views.quality,name='quality'),
    path('cowhealth/',views.cowhealth,name='cowhealth'),
    path('profile/',views.profile,name='profile'),
]

visual/views.py
from django.shortcuts import render
#import urllib2
import urllib.request as urllib2
import json
import time
import requests
from django.contrib.auth.decorators import login_required
from home.models import FarmerProfile

READ_API_KEY='PT8PTFESBBO4W5GK'
CHANNEL_ID= 1058265

# Create your views here.
@login_required
def visual(request):
   a=0
   b=0
   '''
   #while True:
    TS = urllib2.urlopen("http://api.thingspeak.com/channels/1058265/feeds/last.json?api_key=PT8PTFESBBO4W5GK" 
                       #% (CHANNEL_ID,READ_API_KEY))

    response = TS.read()
    data=json.loads(response)

    a = data['created_at']
    b = data['field1']
    #c = data['field2']
    #d = data['field3']
    #print a + "    " + b + "    " + c + "    " + d
    time.sleep(30)   

    TS.close()
    
    with urllib.request.urlopen("https://api.thingspeak.com/channels/1058265/feeds.json?api_key=PT8PTFESBBO4W5GK&results=2") as url:
    #print (url.read())
    a = url.read()
    
    response = requests.get("https://api.thingspeak.com/channels/1058265/feeds.json?api_key=PT8PTFESBBO4W5GK&results=2") 
    if response.status_code == 200:

     a = response.json()
'''
   return render(request, 'visual/visual.html')


def quantity(request):
   return render(request, 'visual/quantity.html')

def quality(request):
   return render(request, 'visual/quality.html')

def cowhealth(request):
   return render(request, 'visual/cowhealth.html')


def profile(request):
   user = request.user
   print(user)
   farmer = FarmerProfile.objects.get(user=user)
   #farmer = FarmerProfile.objects.all()
   return render(request, 'visual/profile.html',{'user':user,'farmer':farmer})

visual/templates/visual/cowhealth.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}

<title>MooMa</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no,shrink-to-fit=no">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="js/bootstrap-transition.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.5.0/css/all.css' integrity='sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU' crossorigin='anonymous'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

<style>
  .navbar-default .navbar-toggle {
      border-color: transparent;
  }
  .dropdown-toggle li a:hover {
      color: #29292c !important;
      border: none;
   outline: none;
   text-decoration: none;
  }
  .dropdown-toggle:hover,
.dropdown-toggle:focus {
  text-decoration: none;
  color: #29292c !important;
}
  .dropdown-menu li a {
      color: #000 !important;
  }
  .dropdown-menu li a:hover {
      background-color: red !important;
  }
  footer{
           background: #05223d;
           padding: 15px 0;
           color:#8d8d8c;
           width: 100%;
           /*
           position:absolute;
           bottom:0;*/
           
      }
       
      ul.bottom_menu li {
           float: left;
           font-size: 14px;
           font-weight: 300;   
           margin-left: 20px;
           list-style: none;
          
      }
      
      ul.bottom_menu li a {
           color: #8d8d8c;
           text-decoration: none;
      
      }
</style>
</head>

<body>
<div class="navbar navbar-fixed-top">
  <nav class="navbar navbar-default navbar-fixed-top"  style="border:0;background:#FEFCFF;padding-right: 5px;padding-top: 5px;font-size: 15px;font-weight: bold;font-family:Montserrat,sans-serif;margin:0;">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <img src="{% static 'images/logo4.png' %}" style="height:59px ; width:59px">
        <img src="{% static 'images/logo3.png' %}" style="height:60px ; width:145px">
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'home:home' %}">Home</a></li>
          <li><a href="{% url 'aboutus:aboutus' %}">About us</a></li>
          <li><a href="{% url 'technology:technology' %}">Technology</a></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Solutions<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="">Milk Collection</a></li>
              <li><a href="">Milk Processing</a></li>
              <li><a href="">Cow trading and Breeding</a></li>
              <li><a href="">B2B Marketplace</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Login<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'farmerlogin:userlogin' %}">Farmer Login</a></li>
              <li><a href="{% url 'financierlogin:userlogin' %}">Financier Login</a></li>
              <li><a href="">Admin Login</a></li>
              <li><a href="{% url 'farmerlogin:userlogout' %}">Logout</a></li>
            </ul>
          </li>
          <li><a href="{% url 'contactus:showform' %}">Contact us</a></li>&nbsp;
        </ul>
      </div>
    </div>
  </nav>


    <nav class="navbar navbar-inverse" style="padding-top:65px;font-size:15px;" >
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myDashboard">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Dashboard</a>
        </div>
        <div class="collapse navbar-collapse" id="myDashboard">
        <ul class="nav navbar-nav navbar">
          <li><a href="{% url 'visual:visual' %}">System Health</a></li>
          <li><a href="{% url 'visual:quantity' %}">Milk Quantity</a></li>
          <li><a href="{% url 'visual:quality' %}">Milk Quality</a></li>
          <li><a href="{% url 'visual:cowhealth' %}">Cow Health</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'visual:profile' %}"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
          <li><a href="{% url 'farmerlogin:userlogout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        </ul>
      </div>
      </div>
    </nav>
</div>

    <div class="container" style="padding-top:160px;text-align:center;">
        <center><h2>Cow Health</h2></center><br><br>
        <div class="row">
          <div class="col-sm-6">
            <iframe width="450" height="260" style="border: 1px solid #fff;" src="https://thingspeak.com/channels/1058269/charts/1?bgcolor=%23ffffff&color=%23d62020&dynamic=true&results=60&title=Ear+Canal+Temperature&type=line"></iframe>
          </div>
          <div class="col-sm-6">
            <iframe width="450" height="260" style="border: 1px solid #fff;" src="https://thingspeak.com/channels/1058269/charts/2?bgcolor=%23ffffff&color=%23d62020&dynamic=true&results=60&title=Pulse+Rate+%28Neck+Strap%29&type=line"></iframe>
          </div>
        </div><br><br>

        <div class="row"></div>
          <div class="col-sm-6">
            <iframe width="450" height="260" style="border: 1px solid #fff;" src="https://thingspeak.com/channels/1058269/charts/3?bgcolor=%23ffffff&color=%23d62020&dynamic=true&results=60&title=Ambient+Temperature+%28%C2%B0C%29&type=line"></iframe>
          </div>
          <div class="col-sm-6">
            <iframe width="450" height="260" style="border: 1px solid #fff;" src="https://thingspeak.com/channels/1058269/charts/4?bgcolor=%23ffffff&color=%23d62020&dynamic=true&results=60&title=Ambient+Humidity+%25&type=line"></iframe>
          </div>
        </div>

    </div>

    <footer >
      <div class="container0" style="padding: 0px 80px;">
        <div class="row">
          <div class="col-md-6 mb-4">
            <p class="crp" style="float:left;margin:0;font-size: 15px;">© 2020 MooMa . All Rights Reserved.</p>
          </div>
    
          <div class="col-md-6 mb-4">
            <ul class="bottom_menu" style="float:right;">
              <li><a href="{% url 'aboutus:aboutus' %}">About Us</a></li>
              <li><a href="#">Career</a></li>
              <li><a href="{% url 'contactus:showform' %}">Contact us</a></li>
              <li><a href="#">Terms of Service</a></li>
              <li><a href="#">Privacy</a></li>
           </ul>
          </div>    
        </div>
    
    
      </div>
    </footer>
</body>
</html>

visual/templates/visual/profile.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}

<title>MooMa</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no,shrink-to-fit=no">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="js/bootstrap-transition.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.5.0/css/all.css' integrity='sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU' crossorigin='anonymous'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<style>

  .navbar-default .navbar-toggle {
      border-color: transparent;
  }
  .dropdown-toggle li a:hover {
      color: #29292c !important;
      border: none;
   outline: none;
   text-decoration: none;
  }
  .dropdown-toggle:hover,
.dropdown-toggle:focus {
  text-decoration: none;
  color: #29292c !important;
}
  .dropdown-menu li a {
      color: #000 !important;
  }
  .dropdown-menu li a:hover {
      background-color: red !important;
  }
  footer{
           background: #05223d;
           padding: 15px 0;
           color:#8d8d8c;
           width: 100%;
           /*
           position:absolute;
           bottom:0;*/
           
      }
       
      ul.bottom_menu li {
           float: left;
           font-size: 14px;
           font-weight: 300;   
           margin-left: 20px;
           list-style: none;
          
      }
      
      ul.bottom_menu li a {
           color: #8d8d8c;
           text-decoration: none;
      
      }
</style>
</head>

<body>
  <div class="navbar navbar-fixed-top">
    <nav class="navbar navbar-default navbar-fixed-top"  style="border:0;background:#FEFCFF;padding-right: 5px;padding-top: 5px;font-size: 15px;font-weight: bold;font-family:Montserrat,sans-serif;margin:0;">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <img src="{% static 'images/logo4.png' %}" style="height:59px ; width:59px">
          <img src="{% static 'images/logo3.png' %}" style="height:60px ; width:145px">
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'home:home' %}">Home</a></li>
            <li><a href="{% url 'aboutus:aboutus' %}">About us</a></li>
            <li><a href="{% url 'technology:technology' %}">Technology</a></li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Solutions<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="">Milk Collection</a></li>
                <li><a href="">Milk Processing</a></li>
                <li><a href="">Cow trading and Breeding</a></li>
                <li><a href="">B2B Marketplace</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Login<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'farmerlogin:userlogin' %}">Farmer Login</a></li>
                <li><a href="{% url 'financierlogin:userlogin' %}">Financier Login</a></li>
                <li><a href="">Admin Login</a></li>
                <li><a href="{% url 'farmerlogin:userlogout' %}">Logout</a></li>
              </ul>
            </li>
            <li><a href="{% url 'contactus:showform' %}">Contact us</a></li>&nbsp;
          </ul>
        </div>
      </div>
    </nav>
  
  
      <nav class="navbar navbar-inverse" style="padding-top:65px;font-size:15px;" >
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myDashboard">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Dashboard</a>
          </div>
          <div class="collapse navbar-collapse" id="myDashboard">
          <ul class="nav navbar-nav navbar">
            <li><a href="{% url 'visual:visual' %}">System Health</a></li>
            <li><a href="{% url 'visual:quantity' %}">Milk Quantity</a></li>
            <li><a href="{% url 'visual:quality' %}">Milk Quality</a></li>
            <li><a href="{% url 'visual:cowhealth' %}">Cow Health</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'visual:profile' %}"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
            <li><a href="{% url 'farmerlogin:userlogout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
          </ul>
        </div>
        </div>
      </nav>
  </div>
  
  <div class="container" style="padding-top:160px">


  <div class="container-fluid">
    <div class="row"  style="width:60%;margin:auto;">
      <div class="well">
            <h2 style="text-decoration:underline;text-align: center;">{{ user.username }}</h2><br>
            <div style="font-size: 18px;margin: auto;">
            <p><strong>Email Id: </strong>&nbsp;{{ user.email }} </p>
            <p><strong>Mooma User Id: </strong>&nbsp;{{ farmer.Mooma_user_id}}</p>
            <p><strong>First Name: </strong>&nbsp;{{ farmer.first_name}}</p>
            <p><strong>Last Name: </strong>&nbsp;{{ farmer.last_name}}</p>
            <p><strong>State: </strong>&nbsp;{{ farmer.state}}</p>
            <p><strong>District: </strong>&nbsp;{{ farmer.district}}</p>
            <p><strong>Sub-District: </strong>&nbsp;{{ farmer.subdistrict}}</p>
            <p><strong>Pincode: </strong>&nbsp;{{ farmer.pincode}}</p>
            <p><strong>Address: </strong>&nbsp;{{ farmer.Address}}</p>
            <p><strong>Phone Number: </strong>&nbsp;{{ farmer.Phone_number}}</p>
            <p><strong>Size of Farm: </strong>&nbsp;{{ farmer.Size_of_farm}}</p>
            <p><strong>Equipment used: </strong>&nbsp;{{ farmer.Equipment_used}}</p>
            <p><strong>Installed Date: </strong>&nbsp;{{ farmer.Installed_date}}</p>
            <p><strong>Breed Types: </strong><br></p>
            {% if farmer.Jersey == True %}<li>Jersey</li>{% endif %}
            {% if farmer.Holstein_Friesian == True %}<li> Holstein Friesian</li> {% endif %}
            {% if farmer.Sahiwal == True %}<li> Sahiwal</li> {% endif %}
            {% if farmer.Khillar == True %}<li> Khillar</li> {% endif %}
            {% if farmer.Gir == True %}<li> Gir </li>{% endif %}
            {% if farmer.Other_breed%}<li>{{farmer.Other_breed}}</li>{% endif %}
            {% if farmer.Mixed_breed%}<li>{{farmer.Mixed_breed}}</li>{% endif %}
            </div>
        </div>

    </div>
  </div>
</div>
<footer >
  <div class="container0" style="padding: 0px 80px;">
    <div class="row">
      <div class="col-md-6 mb-4">
        <p class="crp" style="float:left;margin:0;font-size: 15px;">© 2020 MooMa . All Rights Reserved.</p>
      </div>

      <div class="col-md-6 mb-4">
        <ul class="bottom_menu" style="float:right;">
          <li><a href="{% url 'aboutus:aboutus' %}">About Us</a></li>
          <li><a href="#">Career</a></li>
          <li><a href="{% url 'contactus:showform' %}">Contact us</a></li>
          <li><a href="#">Terms of Service</a></li>
          <li><a href="#">Privacy</a></li>
       </ul>
      </div>    
    </div>


  </div>
</footer>
</body>
</html>