MooMa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('showform/', include('contactus.urls')),
    path('aboutus/', include('aboutus.urls')),
    path('technology/', include('technology.urls')),
    path('farmerlogin/', include('farmerlogin.urls')),
    path('visual/', include('visual.urls')),
    path('financierlogin/', include('financierlogin.urls')),
    path('visualfinancier/', include('visualfinancier.urls')),
]

aboutus/urls.py
from django.urls import re_path, include, path
from . import views

app_name = 'aboutus'

urlpatterns = [

    path('', views.aboutus, name='aboutus'),
]

contactus/urls.py
from django.urls import re_path, include, path
from . import views

app_name = 'contactus'


urlpatterns = [

    path('', views.showform, name='showform'),

]

farmerlogin/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views


app_name = 'farmerlogin'

urlpatterns = [
    path('',views.userlogin,name='userlogin'),
    path('logout/',views.userlogout,name='userlogout'),
    #path('',auth_views.login,{'template_name': 'farmerlogin/login.html'},name='login'),
    path('signup/', views.signup, name='signup'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    path('ajax/load_districts/', views.load_districts, name='load_districts'),
    path('ajax/load_subdistricts/', views.load_subdistricts, name='load_subdistricts'),
    path('ajax/load_pincode/', views.load_pincode, name='load_pincode'),
]

financierlogin/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views


app_name = 'financierlogin'

urlpatterns = [
    path('',views.userlogin,name='userlogin'),
    path('logout/',views.userlogout,name='userlogout'),
    #path('',auth_views.login,{'template_name': 'farmerlogin/login.html'},name='login'),
    path('signup/', views.signup, name='signup'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    path('ajax/load_districts/', views.load_districts, name='load_districts'),
    path('ajax/load_cities/', views.load_cities, name='load_cities'),
    path('ajax/load_banks/', views.load_banks, name='load_banks'),
    path('ajax/load_branches/', views.load_branches, name='load_branches'),
    path('ajax/load_ifscs/', views.load_ifscs, name='load_ifscs'),
]

home/urls.py
from django.urls import re_path, include, path
from . import views

app_name = 'home'

urlpatterns = [
    #path('load/',views.load,name='load'),
    path('', views.home, name='home'),
]

technology/urls.py
from django.urls import re_path, include, path
from . import views

app_name = 'technology'

urlpatterns = [

    path('', views.technology, name='technology'),
]

farmerlogin/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from home.models import FarmerProfile,District,SubDistrict,Pincode
from phonenumber_field.formfields import PhoneNumberField
#from home.models import CustomUser

'''
class SignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=50, required=True)
    last_name = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(max_length=254, help_text='Enter a valid email address')
    Address = forms.CharField(max_length=300)
    #phone_regex = RegexValidator(regex=r'^\?1?\d{9,10}$')
    #Phone_number = models.CharField(validators=[phone_regex], max_length=10, blank=True)
    Phone_number = forms.CharField(max_length=10,help_text='Enter a valid Phone number')
    Size_of_farm = forms.IntegerField()
    Equipment_used = forms.CharField(max_length=300)
    Breed_type = forms.CharField(max_length=50)
    
    class Meta:
        model = User
        fields = [
            'username', 
            'first_name', 
            'last_name', 
            'email',
            'Address',
            'Phone_number',
            'Size_of_farm',
            'Equipment_used',
            'Breed_type',
            'password1', 
            'password2', 
            ]
'''

class SignupForm(UserCreationForm):
    #username = forms.CharField(max_length=50, required=True)
    #last_name = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(max_length=254, help_text='Enter a valid email address',widget=forms.TextInput())    
    

    class Meta:
        model = User
        fields = [
            'username',  
            'email',
            'password1', 
            'password2', 
            ]


class FarmerProfileForm(forms.ModelForm):
    Size_of_farm = forms.IntegerField(widget=forms.TextInput())
    Mooma_user_id = forms.IntegerField(widget=forms.TextInput())
    #Phone_number = forms.BigIntegerField(widget=forms.TextInput())
    #Phone_number = PhoneNumberField(widget=forms.TextInput())
    #Installed_date = forms.DateField(widget=forms.SelectDateWidget(years=range(2017,2030)))
    #subdistrict = forms.ForeignKey(widget=forms.TextInput())

    class Meta:
        model = FarmerProfile
        fields = [ 
            'Mooma_user_id',
            'first_name', 
            'last_name',
            'state',
            'district',
            'subdistrict',
            'pincode',
            'Address',
            'Phone_number',
            'Size_of_farm',
            'Equipment_used',
            'Installed_date',
            'Jersey',
            'Holstein_Friesian',
            'Sahiwal',
            'Khillar',
            'Gir',
            'Other_breed',
            'Mixed_breed'
            ]

        widgets = {
            'Phone_number': forms.TextInput(attrs={'class': 'phoneclass'}),
            'Installed_date': forms.SelectDateWidget(years=range(2017,2030),attrs={'class': 'dateclass'}),
            'state': forms.Select(attrs={'class': 'myclass'}),
            'district': forms.Select(attrs={'class': 'myclass'}),
            'subdistrict': forms.Select(attrs={'class': 'myclass'}),
            'pincode': forms.Select(attrs={'class': 'myclass'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['district'].queryset = District.objects.none()
    
    
        if 'state' in self.data:
            try:
                state_id = int(self.data.get('state'))
                self.fields['district'].queryset = District.objects.filter(state_id=state_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['district'].queryset = self.instance.state.district_set.order_by('name')
    

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['subdistrict'].queryset = SubDistrict.objects.none()
     
        if 'district' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['subdistrict'].queryset = SubDistrict.objects.filter(district_id=district_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['subdistrict'].queryset = self.instance.district.subdistrict_set.order_by('name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['pincode'].queryset = Pincode.objects.none()
     
        if 'subdistrict' in self.data:
            try:
                subdistrict_id = int(self.data.get('subdistrict'))
                self.fields['pincode'].queryset = Pincode.objects.filter(subdistrict_id=subdistrict_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['pincode'].queryset = self.instance.subdistrict.pincode_set.order_by('name')

farmerlogin/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .forms import SignupForm,FarmerProfileForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from home.models import FarmerProfile,State,District,SubDistrict,Pincode,Usertype
#from home.models import FarmerLogin


#@login_required
#def loggedin(request):
#    return HttpResponse("You are logged in !")

#@login_required
def userlogout(request):
    logout(request)
    #messages.info(request, "Logged out successfully!")
    return redirect("home:home")
    

def signup(request):
    msg1=''
    if request.method == 'POST':
        form = SignupForm(request.POST)
        farmerform = FarmerProfileForm(request.POST)
        if form.is_valid() and farmerform.is_valid():
            user = form.save()
            user.is_active = False
            #user.refresh_from_db()
            #user.is_valid = False
            #user.set_password(user.password)
            user.save()
            #user.profile.email = form.cleaned_data.get('email')
            #user.profile.first_name = form.cleaned_data.get('first_name')
            #user.profile.last_name = form.cleaned_data.get('last_name')
            #user.profile.Address = form.cleaned_data.get('Address')
            #user.profile.Phone_number = form.cleaned_data.get('Phone_number')
            #user.profile.Size_of_farm = form.cleaned_data.get('Size_of_farm')
            #user.profile.Equipment_used = form.cleaned_data.get('Equipment_used')
            #user.profile.Breed_type = form.cleaned_data.get('Breed_type')
            profile = farmerform.save(commit=False)
            profile.user=user
            profile.save()
            temp = Usertype.objects.get_or_create(
                        user = user,
                        is_farmer = True,
                        )
            #farmerform.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your MooMa account.'
            message = render_to_string('farmerlogin/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            msg1 = 'Please confirm your email address to complete the registration'
            email.send()
            return render(request, 'farmerlogin/activation.html', {'msg1': msg1})
            #return HttpResponse('Please confirm your email address to complete the registration')

    else:
        form = SignupForm()
        farmerform = FarmerProfileForm()
    return render(request, 'farmerlogin/signup.html', {'form': form,'farmerform':farmerform})



def activate(request, uidb64, token):
    msg2=''
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        farmer = FarmerProfile.objects.get(user=user)
        farmer.email_confirmed = True
        #farmer.is_farmer = True
        farmer.save()
        #user.is_valid = True
        user.save()
        login(request, user)
        return redirect('visual:visual')
        #msg2='Thank you for your email confirmation. Now you can login your account.'
        #return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
        #return HttpResponseRedirect(request, 'farmerlogin/login.html', {'msg2': msg2})
        #return render(request,'farmerlogin/login.html', {'msg2':msg2})
    else:
        msg1='Activation link is expired!'
        return render(request,'farmerlogin/activation.html', {'msg1': msg1})
       

def userlogin(request):
    error=''
    if request.user.is_authenticated:
        return redirect('visual:visual')
    else:
        if request.method == 'POST':
            form = AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(username=username, password=password)
                #print(FarmerProfile.objects.get(user=user)
                #u = FarmerProfile.objects.get(user=user)
                u = Usertype.objects.get(user=user)
                if user is not None and u.is_farmer:
                    login(request, user)
                    #return HttpResponse("You are now logged in as {username}")
                    return redirect('visual:visual')
                
                else:
                    #return HttpResponse("Invalid username or password.")
                    error = "Invalid username or password."
            else:
                #return HttpResponse("Invalid username or password.")
                error = "Invalid username or password."

        form = AuthenticationForm()
        return render(request = request,
                        template_name = "farmerlogin/login.html",
                        context={"form":form,"error":error})



def load_districts(request):
    state_id = request.GET.get('state')
    districts = District.objects.filter(state_id=state_id).order_by('name')

    return render(request, 'farmerlogin/dropdown.html', {'districts': districts})

def load_subdistricts(request):
    district_id = request.GET.get('district')
    subdistricts = SubDistrict.objects.filter(district_id=district_id).order_by('name')

    return render(request, 'farmerlogin/dropdown1.html', {'subdistricts':subdistricts})

def load_pincode(request):
    subdistrict_id = request.GET.get('subdistrict')
    pincodes = Pincode.objects.filter(subdistrict_id=subdistrict_id).order_by('name')

    return render(request, 'farmerlogin/dropdown2.html', {'pincodes':pincodes})

farmerlogin/templates/farmerlogin/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'farmerlogin:activate' uidb64=uid token=token %}
{% endautoescape %}

farmerlogin/templates/farmerlogin/activation.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}

<title>MooMa</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="js/bootstrap-transition.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.5.0/css/all.css' integrity='sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU' crossorigin='anonymous'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<style>
    
body, html {

  font-family: Arial, Helvetica, sans-serif;
}

* {
  box-sizing: border-box;
}

.bg-img {
  /* The image used */
  background-image: url("{% static 'images/farmerbg.png' %}");

  min-height: 380px;
  height: 200px;
  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: relative;
}

/* Add styles to the form container */

.warning {
  padding-top: 40px;
  padding-bottom: 30px;
  color:blue;
  font-size:20px ;
}
.nav-tabs li a {
      color: #777;
  }

  .navbar {
      font-family: Montserrat, sans-serif;
      margin-bottom: 0;
      /*background-color: #2b669a;
      background: -webkit-linear-gradient(to right, #FFFFFF, #FFFFFF);
      background: linear-gradient(to right, #FFFFFF, #FFFFFF);
      */
      background:#FEFCFF;
      border: 0;
      font-size: 15px !important;
      font-weight: bold;
      /*letter-spacing: 1px;
      opacity: 0.8;*/
      padding-top: 5px;
      padding-bottom: 5px;
  }
  .navbar li a, .navbar .navbar-brand {
      color: #707070 !important;
  }
  .navbar-nav li a:hover {
      color: #29292c !important;
  }
  .navbar-nav li.active a {
      color: #fff !important;
      background-color: #29292c !important;
  }
  .navbar-default .navbar-toggle {
      border-color: transparent;
  }
  .dropdown-toggle li a:hover {
      color: #29292c !important;
      border: none;
   outline: none;
   text-decoration: none;
  }
  .dropdown-toggle:hover,
.dropdown-toggle:focus {
  text-decoration: none;
  color: #29292c !important;
}
  .dropdown-menu li a {
      color: #000 !important;
  }
  .dropdown-menu li a:hover {
      background-color: red !important;
  }
  footer{
     background: #05223d;
     padding: 15px 0;
     color:#8d8d8c;
     width: 100%;
     position:absolute;
     bottom:0;
}
 
ul.bottom_menu li {
     float: left;
     font-size: 14px;
     font-weight: 300;   
     margin-left: 20px;
     list-style: none;
    
}

ul.bottom_menu li a {
     color: #8d8d8c;
     text-decoration: none;

}
</style>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <img src="{% static 'images/logo4.png' %}" style="height:59px ; width:59px">
        <img src="{% static 'images/logo3.png' %}" style="height:60px ; width:145px">
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'home:home' %}">Home</a></li>
          <li><a href="{% url 'aboutus:aboutus' %}">About us</a></li>
          <li><a href="{% url 'technology:technology' %}">Technology</a></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Solutions<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="">Milk Collection</a></li>
              <li><a href="">Milk Processing</a></li>
              <li><a href="">Cow trading and Breeding</a></li>
              <li><a href="">B2B Marketplace</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Login<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'farmerlogin:userlogin' %}">Farmer Login</a></li>
              <li><a href="{% url 'financierlogin:userlogin' %}">Financier Login</a></li>
              <li><a href="">Admin Login</a></li>
              <li><a href="{% url 'farmerlogin:userlogout' %}">Logout</a></li>
            </ul>
          </li>
          <li><a href="{% url 'contactus:showform' %}">Contact us</a></li>&nbsp;
        </ul>
      </div>
    </div>
  </nav>


<h2>.</h2>
<div class="warning">
  {% if msg1 %}
      <center> {{ msg1 }}</center>
  {% endif %}
</div>
<br>
<div class="bg-img">
    
</div>

  
<footer >

  <div class="container0" style="padding: 0px 80px;">
    <div class="row">
      <div class="col-md-6 mb-4">
        <p class="crp" style="float:left;margin:0;font-size: 15px;">© 2020 MooMa . All Rights Reserved.</p>
      </div>

      <div class="col-md-6 mb-4">
        <ul class="bottom_menu" style="float:right;">
          <li><a href="{% url 'aboutus:aboutus' %}">About Us</a></li>
          <li><a href="#">Career</a></li>
          <li><a href="{% url 'contactus:showform' %}">Contact us</a></li>
          <li><a href="#">Terms of Service</a></li>
          <li><a href="#">Privacy</a></li>
       </ul>
      </div>    
    </div>


  </div>
</footer>


</body>
</html>

farmerlogin/templates/farmerlogin/login.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}

<title>MooMa</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="js/bootstrap-transition.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.5.0/css/all.css' integrity='sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU' crossorigin='anonymous'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<style>
    
body, html {
 
  font-family: Arial, Helvetica, sans-serif;
}

* {
  box-sizing: border-box;
}

.bg-img {
  /* The image used */
  background-image: url("{% static 'images/farmerbg.png' %}");

  height: 500px;
  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: relative;
}

/* Add styles to the form container */
.container {
  position: absolute;
  right: 0;
  margin-top: 40px;
  margin-right: 100px;
  max-width: 300px;
  height: 390px;
  padding: 40px;
  padding-top: 10px;
  padding-right:10px;
  background-color: white;
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 85%;
  padding: 10px;
  margin: 5px 0 22px 0;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Set a style for the submit button */
.btn {
  background-color: #4CAF50;
  color: white;
  padding: 10px 20px;
  border: none;
  cursor: pointer;
  width: 85%;
  opacity: 0.9;
}

.btn:hover {
  opacity: 1;
}

.nav-tabs li a {
      color: #777;
  }

  .navbar {
      font-family: Montserrat, sans-serif;
      margin-bottom: 0;
      /*background-color: #2b669a;
      background: -webkit-linear-gradient(to right, #FFFFFF, #FFFFFF);
      background: linear-gradient(to right, #FFFFFF, #FFFFFF);
      */
      background:#FEFCFF;
      border: 0;
      font-size: 15px !important;
      font-weight: bold;
      /*letter-spacing: 1px;
      opacity: 0.8;*/
      padding-top: 5px;
      padding-bottom: 5px;
  }
  .navbar li a, .navbar .navbar-brand {
      color: #707070 !important;
  }
  .navbar-nav li a:hover {
      color: #29292c !important;
  }
  .navbar-nav li.active a {
      color: #fff !important;
      background-color: #29292c !important;
  }
  .navbar-default .navbar-toggle {
      border-color: transparent;
  }
  .dropdown-toggle li a:hover {
      color: #29292c !important;
      border: none;
   outline: none;
   text-decoration: none;
  }
  .dropdown-toggle:hover,
.dropdown-toggle:focus {
  text-decoration: none;
  color: #29292c !important;
}
  .dropdown-menu li a {
      color: #000 !important;
  }
  .dropdown-menu li a:hover {
      background-color: red !important;
  }

  footer{
     background: #05223d;
     padding: 15px 0;
     color:#8d8d8c;
     width: 100%;
     position:absolute;
     bottom:0;
}
 
ul.bottom_menu li {
     float: left;
     font-size: 14px;
     font-weight: 300;   
     margin-left: 20px;
     list-style: none;
    
}

ul.bottom_menu li a {
     color: #8d8d8c;
     text-decoration: none;

}
</style>
</head>

<body>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <img src="{% static 'images/logo4.png' %}" style="height:59px ; width:59px">
        <img src="{% static 'images/logo3.png' %}" style="height:60px ; width:145px">
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'home:home' %}">Home</a></li>
          <li><a href="{% url 'aboutus:aboutus' %}">About us</a></li>
          <li><a href="{% url 'technology:technology' %}">Technology</a></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Solutions<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="">Milk Collection</a></li>
              <li><a href="">Milk Processing</a></li>
              <li><a href="">Cow trading and Breeding</a></li>
              <li><a href="">B2B Marketplace</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Login<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'farmerlogin:userlogin' %}">Farmer Login</a></li>
              <li><a href="{% url 'financierlogin:userlogin' %}">Financier Login</a></li>
              <li><a href="">Admin Login</a></li>
              <li><a href="{% url 'farmerlogin:userlogout' %}">Logout</a></li>
            </ul>
          </li>
          <li><a href="{% url 'contactus:showform' %}">Contact us</a></li>&nbsp;
        </ul>
      </div>
    </div>
  </nav>

<h2>Form</h2>
<div class="bg-img">
  <form action="{% url 'farmerlogin:userlogin' %}" method="post" class="container">
    {% csrf_token %}

      <h2>Farmer Login</h2>
  
      <label for="username"><b>Username</b></label>
      <input type="text" placeholder="Enter  Username" name="username" required>
  
      <label for="psw"><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="password" required>
      {% if error %}
                <h4 style="color:red;font-size:15px ;">
                    {{ error }}
                </h4>
      {% endif %}
  
      <button type="submit" class="btn">Login</button><br>
      <label><br>
        <!--
      <a href="{% url 'farmerlogin:signup' %}">Forgot Password?</a></label>-->
      <label>
        Don't have an account yet? <a href="{% url 'farmerlogin:signup' %}">Sign up</a></label>
    </form>
    
  </div>

  
  <footer >
    <div class="container0" style="padding: 0px 80px;">
      <div class="row">
        <div class="col-md-6 mb-4">
          <p class="crp" style="float:left;margin:0;font-size: 15px;">© 2020 MooMa . All Rights Reserved.</p>
        </div>
  
        <div class="col-md-6 mb-4">
          <ul class="bottom_menu" style="float:right;">
            <li><a href="{% url 'aboutus:aboutus' %}">About Us</a></li>
            <li><a href="#">Career</a></li>
            <li><a href="{% url 'contactus:showform' %}">Contact us</a></li>
            <li><a href="#">Terms of Service</a></li>
            <li><a href="#">Privacy</a></li>
         </ul>
        </div>    
      </div>
  
  
    </div>
  </footer>
  
  

</body>
</html>